scorbot:
  # Publicar todos los estados de las articulaciones
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Controladores de Posición
  m1_position_controller:
    type: effort_controllers/JointPositionController
    joint: j1
    pid: {p: 1000.0,i: 2.0,d: 1.2}

  m2_position_controller:
    type: effort_controllers/JointPositionController
    joint: j2
    pid: {p: 1000.0,i: 2.0,d: 1.2}

  m3_position_controller:
    type: effort_controllers/JointPositionController
    joint: j3
    pid: {p: 1000.0,i: 2.0,d: 1.2}

  m4_position_controller:
    type: effort_controllers/JointPositionController
    joint: j4
    pid: {p: 1000.0,i: 2.0,d: 1.2}

  m5_position_controller:
    type: effort_controllers/JointPositionController
    joint: j5
    pid: {p: 1000.0,i: 2.0,d: 1.2}